[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tasks"
version = "0.1.0"
dependencies = [
    "textual"
]

[project.scripts]
tasks = "tasks.tui.main:main"
