[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tasks"
version = "0.0.1"
dependencies = [
    "typer"
]

[project.optional-dependencies]
tui = ["textual"]

[project.scripts]
tasks = "tasks.cli.main:app"
