[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "taskmate"
version = "0.1.0"
dependencies = [
    "textual"
]

[project.scripts]
tm = "taskmate.tui.main:main"
